### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by econwang** [B1naryStudio/npp_pyjedi#1]
I install the dll to plugin folder, then can not open notepad++

My enviroment: x64 anaconda python 2.7, does it due to the x64?

**Comment by real-artswan** [comment]
I'm not familar with anaconda but yes you need x86 (32bit) python installation. Notepad++ is x86 itself so plugins must be x86 too. And this plugin uses python dll so python must be x86 as well.

**Comment by econwang** [comment]
thanks
